### this script uses all the data pre-calculated in DWB 1 and DWB 2... and actually returns a DWB output
### use the data written by the previous sections as "baseline", and jump in here to substitute in new sources

setwd("E:/NMSU/interp-engine-personal/TEST FULL WORKFLOW")

require(raster)
require(tidyverse)
require(sf)
require(dplyr)

source("Functions/dwb_calc.r")
source("Functions/evalbyeid.r")
source("Functions/local-functions.r")
load("Input/cached-NASIS-data.Rda")


## this project code is prefixed to all final & intermediate outputs; used for file organization
## files generated in step 2 will use this code; they must match exactly
projectcode <- "UTGrand500"

## define master crs, all files will be transformed into this
crs <- raster::crs("+init=epsg:5070")

## load study area using sf
sf.studyarea <- 
  sf::st_read(dsn = "E:/NMSU/GIS/Utah_County_Boundaries-shp", layer = "Counties") %>%
  subset(NAME == "GRAND") %>% st_transform(crs) %>% st_make_valid()


### 1 load base rasters ####
## find rasters as generated by step 2
paths <- list.files(path = paste0("Input/NASIS Property Rasters/", projectcode), 
                    pattern = paste0(projectcode,".*tif$"), 
                    full.names = T)

## get the layer names from the file basenames, dropping prefix and extension
names <- basename(paths) %>% 
  gsub(pattern = paste0(projectcode, "_"), replacement = "") %>%
  gsub(pattern = ".tif", replacement = "")

brk <- brick(sapply(paths, raster)) %>% projectRaster(crs = crs)
names(brk) <- names
rm(names, paths)

### 2 sub in new data sources ####
brkold <- brk

brk$slope_r <- raster("E:/NMSU/Data/Slope/slope_pct_ut.tif") %>% projectRaster(brk) %>% mask(sf.studyarea)
brk$wt <- raster("E:/NMSU/Data/wtdept_ut.tif") %>% projectRaster(brk) %>% mask(sf.studyarea)


### 3 calculate dwb ####

out1 <- dwb_calc(brk)
out2 <- dwb_calc(brkold)

plot(out1$dwb)
plot(out2$dwb)
